[project]
name = "backend"
version = "0.1.0"
description = "FastAPI backend for BaselHacks PAX document processing"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.120.4",
    "python-multipart>=0.0.20",
    "uvicorn>=0.38.0",
]
